spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChinPangLung/eureka-common-service/tree/master/config-repo/
          searchPaths: spring_cloud_in_action/config-repo
          username: ChinPangLung
          password: Lung921211
server:
  port: 7001