spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChinPangLung/config-repo #git仓库的地址；file://${user.name}/config-repo这是本地文件路径配置的方式，只限于用于开发使用
          searchPaths: spring_cloud_in_action/config-repo
          username: ChinPangLung
          password: Lung921211
      discovery:
        enabled: true
server:
  port: 7001
eureka:
  client:
      serviceUrl:
        defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/