spring:
  application:
    name: service-user-client-fegin
server:
  port: 9001
fegin:
  hystrix:
     enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/