spring:
  application:
    name: service-user-client-fegin
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/
feign:
  hystrix:
    enabled: true
#这个鬼设置需要在最后才会生效