server:
  port: 8763
spring:
  application:
    name: service-register
eureka:
  instance:
    prefer-ip-address: false
    hostname: peer2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0